// Package ascii85 is a drop-in fast path for encoding/ascii85, the Adobe/btoa
// base-85 encoding. The bulk of both directions runs a SIMD kernel generated by
// go-asmgen on amd64/ppc64le/s390x/riscv64/loong64, and on arm64 with Go 1.27+
// (the NEON kernel needs integer vector multiplies that the arm64 assembler only
// gained in Go 1.27; stable Go falls back to a fused scalar path on arm64). Everything the kernel must not guess about — encoding's all-zero "z"
// shortcut and short trailing fragment, decoding's whitespace, "z", short/invalid
// groups, flush, and CorruptInputError offsets — is delegated to encoding/ascii85,
// so output, errors, and offsets are byte-identical to it.
//
// Encode: the base-85 challenge is the repeated division by 85. The kernel avoids
// it with a reciprocal multiply: for any 32-bit v, v/85 == (v*0xC0C0C0C1)>>32>>6
// (verified exact over all 2^32 values), and the remainder is v - q*85. Five
// such steps yield the five base-85 digits per 4-byte group.
//
// Decode is the inverse: each 5-char group is a base-85 multiply-accumulate
// (((c0*85+c1)*85+c2)*85+c3)*85+c4. The kernel only ever sees clean runs of
// 5-char groups whose bytes are all regular digits ('!'..'u'); whitespace, "z",
// and short/invalid groups bail to the stdlib so behaviour stays identical.
package ascii85

import "encoding/ascii85"

// CorruptInputError is re-exported so callers can type-assert decode errors
// exactly as they would with encoding/ascii85.
type CorruptInputError = ascii85.CorruptInputError

// MaxEncodedLen returns the maximum length of an encoding of n source bytes.
func MaxEncodedLen(n int) int { return ascii85.MaxEncodedLen(n) }

// Encode encodes src into at most MaxEncodedLen(len(src)) bytes of dst,
// returning the actual number of bytes written. Output is byte-identical to
// encoding/ascii85.Encode (including the "z" shortcut for all-zero groups).
//
// The encoding handles 4-byte chunks, using a special encoding for the last
// fragment, so Encode is not appropriate for use on individual blocks of a
// large data stream. Use encoding/ascii85.NewEncoder for streaming.
func Encode(dst, src []byte) int {
	n := 0
	// Process maximal runs of complete 4-byte groups that contain no all-zero
	// group with the SIMD kernel (each such group encodes to exactly 5 chars).
	// An all-zero group, or the short trailing fragment, is handed to the
	// standard library so the "z" shortcut and tail stay byte-identical.
	for len(src) >= 4 {
		// Find the length (in whole groups) of the leading run with no zero group.
		groups := 0
		for off := 0; off+4 <= len(src); off += 4 {
			if src[off] == 0 && src[off+1] == 0 && src[off+2] == 0 && src[off+3] == 0 {
				break
			}
			groups++
		}
		if groups > 0 {
			w := encodeSIMD(dst, src, groups)
			dst = dst[w:]
			src = src[groups*4:]
			n += w
			continue
		}
		// Leading group is all zero: let the stdlib emit the single 'z'.
		w := ascii85.Encode(dst, src[:4])
		dst = dst[w:]
		src = src[4:]
		n += w
	}
	// Trailing fragment (0..3 bytes).
	if len(src) > 0 {
		n += ascii85.Encode(dst, src)
	}
	return n
}
