//go:build arm64 && go1.27

package ascii85

// decodeGroups decodes blocks*4 groups of 5 base-85 chars into 4 bytes each (20
// chars -> 16 bytes per block) via NEON. Generated by go-asmgen
// (decode_arm64_gen.go), in decode_arm64.s. It needs an integer NEON multiply
// (VMUL) for the base-85 multiply-accumulate, which Go's arm64 assembler only
// gained in Go 1.27, so this path is //go:build go1.27 and the stable build
// falls back to the scalar decode_generic.go. The caller guarantees every char
// is a regular base-85 digit ('!'..'u'), so each group yields exactly 4 bytes.
func decodeGroups(dst, src []byte, blocks int)

// decodeSIMD decodes the leading run of clean groups into 4 bytes each, using the
// NEON kernel for whole 4-group blocks and a scalar tail for the (groups&3)
// remainder.
func decodeSIMD(dst, src []byte, groups int) {
	blocks := groups / 4
	if blocks > 0 {
		decodeGroups(dst, src, blocks)
	}
	done := blocks * 4
	if rem := groups - done; rem > 0 {
		decodeTail(dst[done*4:], src[done*5:], rem)
	}
}
