// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·decodeGroups(SB), NOSPLIT, $0-56
	MOV dst_base+0(FP), X5
	MOV src_base+24(FP), X6
	MOV blocks+48(FP), X7
	VSETIVLI $16, E8, M1, TA, MA, X28
	MOV $d85gath<>(SB), X29
	VLE8V (X29), V20
	MOV $d85bswap<>(SB), X29
	VLE8V (X29), V21
	MOV $33, X30
	MOV $85, X31
	BEQ X7, X0, done
loop:
	VSETIVLI $16, E8, M1, TA, MA, X28
	VLE8V (X6), V0
	VRGATHERVV V20, V0, V1
	ADD $1, X6, X29
	VLE8V (X29), V0
	VRGATHERVV V20, V0, V2
	ADD $2, X6, X29
	VLE8V (X29), V0
	VRGATHERVV V20, V0, V3
	ADD $3, X6, X29
	VLE8V (X29), V0
	VRGATHERVV V20, V0, V4
	ADD $4, X6, X29
	VLE8V (X29), V0
	VRGATHERVV V20, V0, V5
	VSETIVLI $4, E32, M1, TA, MA, X28
	VSUBVX X30, V1, V1
	VSUBVX X30, V2, V2
	VSUBVX X30, V3, V3
	VSUBVX X30, V4, V4
	VSUBVX X30, V5, V5
	VMULVX X31, V1, V1
	VADDVV V2, V1, V1
	VMULVX X31, V1, V1
	VADDVV V3, V1, V1
	VMULVX X31, V1, V1
	VADDVV V4, V1, V1
	VMULVX X31, V1, V1
	VADDVV V5, V1, V1
	VSETIVLI $16, E8, M1, TA, MA, X28
	VRGATHERVV V21, V1, V0
	VSE8V V0, (X5)
	ADD $20, X6
	ADD $16, X5
	ADD $-1, X7
	BNE X7, X0, loop
done:
	RET

DATA d85gath<>+0(SB)/1, $0x00
DATA d85gath<>+1(SB)/1, $0xff
DATA d85gath<>+2(SB)/1, $0xff
DATA d85gath<>+3(SB)/1, $0xff
DATA d85gath<>+4(SB)/1, $0x05
DATA d85gath<>+5(SB)/1, $0xff
DATA d85gath<>+6(SB)/1, $0xff
DATA d85gath<>+7(SB)/1, $0xff
DATA d85gath<>+8(SB)/1, $0x0a
DATA d85gath<>+9(SB)/1, $0xff
DATA d85gath<>+10(SB)/1, $0xff
DATA d85gath<>+11(SB)/1, $0xff
DATA d85gath<>+12(SB)/1, $0x0f
DATA d85gath<>+13(SB)/1, $0xff
DATA d85gath<>+14(SB)/1, $0xff
DATA d85gath<>+15(SB)/1, $0xff
GLOBL d85gath<>(SB), RODATA|NOPTR, $16

DATA d85bswap<>+0(SB)/1, $0x03
DATA d85bswap<>+1(SB)/1, $0x02
DATA d85bswap<>+2(SB)/1, $0x01
DATA d85bswap<>+3(SB)/1, $0x00
DATA d85bswap<>+4(SB)/1, $0x07
DATA d85bswap<>+5(SB)/1, $0x06
DATA d85bswap<>+6(SB)/1, $0x05
DATA d85bswap<>+7(SB)/1, $0x04
DATA d85bswap<>+8(SB)/1, $0x0b
DATA d85bswap<>+9(SB)/1, $0x0a
DATA d85bswap<>+10(SB)/1, $0x09
DATA d85bswap<>+11(SB)/1, $0x08
DATA d85bswap<>+12(SB)/1, $0x0f
DATA d85bswap<>+13(SB)/1, $0x0e
DATA d85bswap<>+14(SB)/1, $0x0d
DATA d85bswap<>+15(SB)/1, $0x0c
GLOBL d85bswap<>(SB), RODATA|NOPTR, $16

