// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·decodeGroups(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ blocks+48(FP), CX
	MOVOU d85gath<>+0(SB), X8
	MOVOU d85c33<>+0(SB), X9
	MOVOU d85c85<>+0(SB), X10
	MOVOU d85bswap<>+0(SB), X11
	TESTQ CX, CX
	JZ done
blkloop:
	MOVOU 0(SI), X0
	PSHUFB X8, X0
	PSUBL X9, X0
	MOVOU 1(SI), X1
	PSHUFB X8, X1
	PSUBL X9, X1
	MOVOU 2(SI), X2
	PSHUFB X8, X2
	PSUBL X9, X2
	MOVOU 3(SI), X3
	PSHUFB X8, X3
	PSUBL X9, X3
	MOVOU 4(SI), X4
	PSHUFB X8, X4
	PSUBL X9, X4
	PMULLD X10, X0
	PADDL X1, X0
	PMULLD X10, X0
	PADDL X2, X0
	PMULLD X10, X0
	PADDL X3, X0
	PMULLD X10, X0
	PADDL X4, X0
	PSHUFB X11, X0
	MOVOU X0, (DI)
	ADDQ $20, SI
	ADDQ $16, DI
	DECQ CX
	JNZ blkloop
done:
	RET

DATA d85gath<>+0(SB)/1, $0x00
DATA d85gath<>+1(SB)/1, $0x80
DATA d85gath<>+2(SB)/1, $0x80
DATA d85gath<>+3(SB)/1, $0x80
DATA d85gath<>+4(SB)/1, $0x05
DATA d85gath<>+5(SB)/1, $0x80
DATA d85gath<>+6(SB)/1, $0x80
DATA d85gath<>+7(SB)/1, $0x80
DATA d85gath<>+8(SB)/1, $0x0a
DATA d85gath<>+9(SB)/1, $0x80
DATA d85gath<>+10(SB)/1, $0x80
DATA d85gath<>+11(SB)/1, $0x80
DATA d85gath<>+12(SB)/1, $0x0f
DATA d85gath<>+13(SB)/1, $0x80
DATA d85gath<>+14(SB)/1, $0x80
DATA d85gath<>+15(SB)/1, $0x80
GLOBL d85gath<>(SB), RODATA|NOPTR, $16

DATA d85c33<>+0(SB)/1, $0x21
DATA d85c33<>+1(SB)/1, $0x00
DATA d85c33<>+2(SB)/1, $0x00
DATA d85c33<>+3(SB)/1, $0x00
DATA d85c33<>+4(SB)/1, $0x21
DATA d85c33<>+5(SB)/1, $0x00
DATA d85c33<>+6(SB)/1, $0x00
DATA d85c33<>+7(SB)/1, $0x00
DATA d85c33<>+8(SB)/1, $0x21
DATA d85c33<>+9(SB)/1, $0x00
DATA d85c33<>+10(SB)/1, $0x00
DATA d85c33<>+11(SB)/1, $0x00
DATA d85c33<>+12(SB)/1, $0x21
DATA d85c33<>+13(SB)/1, $0x00
DATA d85c33<>+14(SB)/1, $0x00
DATA d85c33<>+15(SB)/1, $0x00
GLOBL d85c33<>(SB), RODATA|NOPTR, $16

DATA d85c85<>+0(SB)/1, $0x55
DATA d85c85<>+1(SB)/1, $0x00
DATA d85c85<>+2(SB)/1, $0x00
DATA d85c85<>+3(SB)/1, $0x00
DATA d85c85<>+4(SB)/1, $0x55
DATA d85c85<>+5(SB)/1, $0x00
DATA d85c85<>+6(SB)/1, $0x00
DATA d85c85<>+7(SB)/1, $0x00
DATA d85c85<>+8(SB)/1, $0x55
DATA d85c85<>+9(SB)/1, $0x00
DATA d85c85<>+10(SB)/1, $0x00
DATA d85c85<>+11(SB)/1, $0x00
DATA d85c85<>+12(SB)/1, $0x55
DATA d85c85<>+13(SB)/1, $0x00
DATA d85c85<>+14(SB)/1, $0x00
DATA d85c85<>+15(SB)/1, $0x00
GLOBL d85c85<>(SB), RODATA|NOPTR, $16

DATA d85bswap<>+0(SB)/1, $0x03
DATA d85bswap<>+1(SB)/1, $0x02
DATA d85bswap<>+2(SB)/1, $0x01
DATA d85bswap<>+3(SB)/1, $0x00
DATA d85bswap<>+4(SB)/1, $0x07
DATA d85bswap<>+5(SB)/1, $0x06
DATA d85bswap<>+6(SB)/1, $0x05
DATA d85bswap<>+7(SB)/1, $0x04
DATA d85bswap<>+8(SB)/1, $0x0b
DATA d85bswap<>+9(SB)/1, $0x0a
DATA d85bswap<>+10(SB)/1, $0x09
DATA d85bswap<>+11(SB)/1, $0x08
DATA d85bswap<>+12(SB)/1, $0x0f
DATA d85bswap<>+13(SB)/1, $0x0e
DATA d85bswap<>+14(SB)/1, $0x0d
DATA d85bswap<>+15(SB)/1, $0x0c
GLOBL d85bswap<>(SB), RODATA|NOPTR, $16

