// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·decodeGroups(SB), NOSPLIT, $0-56
	MOVV dst_base+0(FP), R4
	MOVV src_base+24(FP), R5
	MOVV blocks+48(FP), R6
	MOVV $d85c33<>(SB), R7
	VMOVQ (R7), V22
	MOVV $d85c85<>(SB), R7
	VMOVQ (R7), V21
	MOVV $d85gath<>(SB), R7
	VMOVQ (R7), V23
	MOVV $d85bswap<>(SB), R7
	VMOVQ (R7), V24
	VXORV V28, V28, V28
	BEQ R6, R0, done
loop:
	VMOVQ (R5), V0
	VSHUFB V23, V0, V28, V1
	VSUBW V22, V1, V1
	ADDV $1, R5, R7
	VMOVQ (R7), V0
	VSHUFB V23, V0, V28, V2
	VSUBW V22, V2, V2
	ADDV $2, R5, R7
	VMOVQ (R7), V0
	VSHUFB V23, V0, V28, V3
	VSUBW V22, V3, V3
	ADDV $3, R5, R7
	VMOVQ (R7), V0
	VSHUFB V23, V0, V28, V4
	VSUBW V22, V4, V4
	ADDV $4, R5, R7
	VMOVQ (R7), V0
	VSHUFB V23, V0, V28, V5
	VSUBW V22, V5, V5
	VMULW V21, V1, V1
	VADDW V2, V1, V1
	VMULW V21, V1, V1
	VADDW V3, V1, V1
	VMULW V21, V1, V1
	VADDW V4, V1, V1
	VMULW V21, V1, V1
	VADDW V5, V1, V1
	VSHUFB V24, V1, V28, V0
	VMOVQ V0, (R4)
	ADDV $20, R5, R5
	ADDV $16, R4, R4
	ADDV $-1, R6, R6
	BNE R6, R0, loop
done:
	RET

DATA d85c33<>+0(SB)/1, $0x21
DATA d85c33<>+1(SB)/1, $0x00
DATA d85c33<>+2(SB)/1, $0x00
DATA d85c33<>+3(SB)/1, $0x00
DATA d85c33<>+4(SB)/1, $0x21
DATA d85c33<>+5(SB)/1, $0x00
DATA d85c33<>+6(SB)/1, $0x00
DATA d85c33<>+7(SB)/1, $0x00
DATA d85c33<>+8(SB)/1, $0x21
DATA d85c33<>+9(SB)/1, $0x00
DATA d85c33<>+10(SB)/1, $0x00
DATA d85c33<>+11(SB)/1, $0x00
DATA d85c33<>+12(SB)/1, $0x21
DATA d85c33<>+13(SB)/1, $0x00
DATA d85c33<>+14(SB)/1, $0x00
DATA d85c33<>+15(SB)/1, $0x00
GLOBL d85c33<>(SB), RODATA|NOPTR, $16

DATA d85c85<>+0(SB)/1, $0x55
DATA d85c85<>+1(SB)/1, $0x00
DATA d85c85<>+2(SB)/1, $0x00
DATA d85c85<>+3(SB)/1, $0x00
DATA d85c85<>+4(SB)/1, $0x55
DATA d85c85<>+5(SB)/1, $0x00
DATA d85c85<>+6(SB)/1, $0x00
DATA d85c85<>+7(SB)/1, $0x00
DATA d85c85<>+8(SB)/1, $0x55
DATA d85c85<>+9(SB)/1, $0x00
DATA d85c85<>+10(SB)/1, $0x00
DATA d85c85<>+11(SB)/1, $0x00
DATA d85c85<>+12(SB)/1, $0x55
DATA d85c85<>+13(SB)/1, $0x00
DATA d85c85<>+14(SB)/1, $0x00
DATA d85c85<>+15(SB)/1, $0x00
GLOBL d85c85<>(SB), RODATA|NOPTR, $16

DATA d85gath<>+0(SB)/1, $0x00
DATA d85gath<>+1(SB)/1, $0x10
DATA d85gath<>+2(SB)/1, $0x10
DATA d85gath<>+3(SB)/1, $0x10
DATA d85gath<>+4(SB)/1, $0x05
DATA d85gath<>+5(SB)/1, $0x10
DATA d85gath<>+6(SB)/1, $0x10
DATA d85gath<>+7(SB)/1, $0x10
DATA d85gath<>+8(SB)/1, $0x0a
DATA d85gath<>+9(SB)/1, $0x10
DATA d85gath<>+10(SB)/1, $0x10
DATA d85gath<>+11(SB)/1, $0x10
DATA d85gath<>+12(SB)/1, $0x0f
DATA d85gath<>+13(SB)/1, $0x10
DATA d85gath<>+14(SB)/1, $0x10
DATA d85gath<>+15(SB)/1, $0x10
GLOBL d85gath<>(SB), RODATA|NOPTR, $16

DATA d85bswap<>+0(SB)/1, $0x03
DATA d85bswap<>+1(SB)/1, $0x02
DATA d85bswap<>+2(SB)/1, $0x01
DATA d85bswap<>+3(SB)/1, $0x00
DATA d85bswap<>+4(SB)/1, $0x07
DATA d85bswap<>+5(SB)/1, $0x06
DATA d85bswap<>+6(SB)/1, $0x05
DATA d85bswap<>+7(SB)/1, $0x04
DATA d85bswap<>+8(SB)/1, $0x0b
DATA d85bswap<>+9(SB)/1, $0x0a
DATA d85bswap<>+10(SB)/1, $0x09
DATA d85bswap<>+11(SB)/1, $0x08
DATA d85bswap<>+12(SB)/1, $0x0f
DATA d85bswap<>+13(SB)/1, $0x0e
DATA d85bswap<>+14(SB)/1, $0x0d
DATA d85bswap<>+15(SB)/1, $0x0c
GLOBL d85bswap<>(SB), RODATA|NOPTR, $16

