//go:build ppc64le

package ascii85

// decodeGroups decodes blocks*4 groups of 5 base-85 chars into 4 bytes each (20
// chars -> 16 bytes per block) via the VSX/AltiVec vector facility. Generated by
// go-asmgen (decode_ppc64x_gen.go), in decode_ppc64x.s. The caller guarantees
// every char is a regular base-85 digit ('!'..'u'). The kernel is built entirely
// from ISA-2.07 (POWER8-baseline) ops — the element-order vector load/store is
// emitted as LXVD2X/STXVD2X + a VPERM byte-reversal instead of the ISA-3.0
// LXVB16X/STXVB16X — so it runs natively on POWER8 too (gated by hasVSX, shared
// with the encode kernel).
func decodeGroups(dst, src []byte, blocks int)

// decodeSIMD decodes the leading run of clean groups into 4 bytes each, using the
// vector kernel for whole 4-group blocks and a scalar tail for the (groups&3)
// remainder. When hasVSX is false (forced off in tests) it decodes every group
// with a tight scalar loop.
func decodeSIMD(dst, src []byte, groups int) {
	if !hasVSX {
		decodeScalar(dst, src, groups)
		return
	}
	blocks := groups / 4
	if blocks > 0 {
		decodeGroups(dst, src, blocks)
	}
	done := blocks * 4
	if rem := groups - done; rem > 0 {
		decodeTail(dst[done*4:], src[done*5:], rem)
	}
}

// decodeScalar decodes the leading run of clean 5-char groups with a tight scalar
// loop (the POWER8 fallback). The caller guarantees src[:groups*5] is groups
// whole groups of regular base-85 digits ('!'..'u') and dst has room for
// groups*4 bytes, so each group always yields exactly 4 bytes.
func decodeScalar(dst, src []byte, groups int) {
	di := 0
	for g := 0; g < groups; g++ {
		s := src[g*5:]
		v := (((uint32(s[0]-'!')*85+uint32(s[1]-'!'))*85+
			uint32(s[2]-'!'))*85+uint32(s[3]-'!'))*85 + uint32(s[4]-'!')
		d := dst[di : di+4 : di+4]
		d[0] = byte(v >> 24)
		d[1] = byte(v >> 16)
		d[2] = byte(v >> 8)
		d[3] = byte(v)
		di += 4
	}
}
