//go:build amd64

package ascii85

// decodeGroups decodes blocks*4 groups of 5 base-85 chars into 4 bytes each (20
// chars -> 16 bytes per block) via SSE. Generated by go-asmgen (decode_gen.go),
// in decode_amd64.s. The caller guarantees every char is a regular base-85 digit
// ('!'..'u'), so each group yields exactly 4 bytes.
func decodeGroups(dst, src []byte, blocks int)

// decodeSIMD decodes the leading run of clean groups (which the caller guarantees
// are whole 5-char groups of regular base-85 digits, with dst room for 4 bytes
// each) into 4 bytes each, using the SSE kernel for whole 4-group blocks and a
// scalar tail for the (groups&3) remainder.
func decodeSIMD(dst, src []byte, groups int) {
	blocks := groups / 4
	if blocks > 0 {
		decodeGroups(dst, src, blocks)
	}
	done := blocks * 4
	if rem := groups - done; rem > 0 {
		decodeTail(dst[done*4:], src[done*5:], rem)
	}
}
