// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·decodeGroups(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD blocks+48(FP), R3
	MOVD $d85c33<>(SB), R4
	VL (R4), V20
	MOVD $d85c85<>(SB), R4
	VL (R4), V21
	MOVD $d85gath<>(SB), R4
	VL (R4), V22
	VZERO V19
	CMPBEQ R3, $0, done
loop:
	VL 0(R2), V0
	VPERM V0, V19, V22, V0
	VSF V20, V0, V0
	VL 1(R2), V1
	VPERM V1, V19, V22, V1
	VSF V20, V1, V1
	VL 2(R2), V2
	VPERM V2, V19, V22, V2
	VSF V20, V2, V2
	VL 3(R2), V3
	VPERM V3, V19, V22, V3
	VSF V20, V3, V3
	VL 4(R2), V4
	VPERM V4, V19, V22, V4
	VSF V20, V4, V4
	VMLF V0, V21, V0
	VAF V1, V0, V0
	VMLF V0, V21, V0
	VAF V2, V0, V0
	VMLF V0, V21, V0
	VAF V3, V0, V0
	VMLF V0, V21, V0
	VAF V4, V0, V0
	VST V0, (R1)
	ADD $20, R2
	ADD $16, R1
	ADD $-1, R3
	CMPBNE R3, $0, loop
done:
	RET

DATA d85c33<>+0(SB)/1, $0x00
DATA d85c33<>+1(SB)/1, $0x00
DATA d85c33<>+2(SB)/1, $0x00
DATA d85c33<>+3(SB)/1, $0x21
DATA d85c33<>+4(SB)/1, $0x00
DATA d85c33<>+5(SB)/1, $0x00
DATA d85c33<>+6(SB)/1, $0x00
DATA d85c33<>+7(SB)/1, $0x21
DATA d85c33<>+8(SB)/1, $0x00
DATA d85c33<>+9(SB)/1, $0x00
DATA d85c33<>+10(SB)/1, $0x00
DATA d85c33<>+11(SB)/1, $0x21
DATA d85c33<>+12(SB)/1, $0x00
DATA d85c33<>+13(SB)/1, $0x00
DATA d85c33<>+14(SB)/1, $0x00
DATA d85c33<>+15(SB)/1, $0x21
GLOBL d85c33<>(SB), RODATA|NOPTR, $16

DATA d85c85<>+0(SB)/1, $0x00
DATA d85c85<>+1(SB)/1, $0x00
DATA d85c85<>+2(SB)/1, $0x00
DATA d85c85<>+3(SB)/1, $0x55
DATA d85c85<>+4(SB)/1, $0x00
DATA d85c85<>+5(SB)/1, $0x00
DATA d85c85<>+6(SB)/1, $0x00
DATA d85c85<>+7(SB)/1, $0x55
DATA d85c85<>+8(SB)/1, $0x00
DATA d85c85<>+9(SB)/1, $0x00
DATA d85c85<>+10(SB)/1, $0x00
DATA d85c85<>+11(SB)/1, $0x55
DATA d85c85<>+12(SB)/1, $0x00
DATA d85c85<>+13(SB)/1, $0x00
DATA d85c85<>+14(SB)/1, $0x00
DATA d85c85<>+15(SB)/1, $0x55
GLOBL d85c85<>(SB), RODATA|NOPTR, $16

DATA d85gath<>+0(SB)/1, $0x10
DATA d85gath<>+1(SB)/1, $0x10
DATA d85gath<>+2(SB)/1, $0x10
DATA d85gath<>+3(SB)/1, $0x00
DATA d85gath<>+4(SB)/1, $0x10
DATA d85gath<>+5(SB)/1, $0x10
DATA d85gath<>+6(SB)/1, $0x10
DATA d85gath<>+7(SB)/1, $0x05
DATA d85gath<>+8(SB)/1, $0x10
DATA d85gath<>+9(SB)/1, $0x10
DATA d85gath<>+10(SB)/1, $0x10
DATA d85gath<>+11(SB)/1, $0x0a
DATA d85gath<>+12(SB)/1, $0x10
DATA d85gath<>+13(SB)/1, $0x10
DATA d85gath<>+14(SB)/1, $0x10
DATA d85gath<>+15(SB)/1, $0x0f
GLOBL d85gath<>(SB), RODATA|NOPTR, $16

