//go:build arm64 && go1.27

package ascii85

import "encoding/ascii85"

// encodeGroups encodes blocks*4 groups of 4 input bytes into 5 base-85 chars
// each (16 input bytes -> 20 chars per block) via NEON. Generated by go-asmgen
// (encode_arm64_gen.go), in encode_arm64.s. It needs an integer NEON multiply
// (VUMULL/VMUL) for the /85 reciprocal divide, which Go's arm64 assembler only
// gained in Go 1.27, so this path is //go:build go1.27 and the stable build
// falls back to the scalar encode_generic.go. The caller guarantees none of
// those groups is all-zero, so every group expands to exactly 5 chars.
func encodeGroups(dst, src []byte, blocks int)

// encodeSIMD encodes the leading run of groups (which the caller guarantees
// contains no all-zero group) into 5 chars each, using the NEON kernel for whole
// 4-group blocks and the standard library for the (groups&3) remainder. It
// returns the number of bytes written.
func encodeSIMD(dst, src []byte, groups int) int {
	blocks := groups / 4
	if blocks > 0 {
		encodeGroups(dst, src, blocks)
	}
	done := blocks * 4
	w := done * 5
	if rem := groups - done; rem > 0 {
		w += ascii85.Encode(dst[w:], src[done*4:groups*4])
	}
	return w
}
