// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·encodeGroups(SB), NOSPLIT, $0-56
	MOVV dst_base+0(FP), R4
	MOVV src_base+24(FP), R5
	MOVV blocks+48(FP), R6
	MOVV $a85mrec<>(SB), R7
	VMOVQ (R7), V20
	MOVV $a85c85<>(SB), R7
	VMOVQ (R7), V21
	MOVV $a85c33<>(SB), R7
	VMOVQ (R7), V22
	MOVV $a85bswap<>(SB), R7
	VMOVQ (R7), V23
	MOVV $a85expA<>(SB), R7
	VMOVQ (R7), V24
	MOVV $a85d4A<>(SB), R7
	VMOVQ (R7), V25
	MOVV $a85expB<>(SB), R7
	VMOVQ (R7), V26
	MOVV $a85d4B<>(SB), R7
	VMOVQ (R7), V27
	VXORV V28, V28, V28
	BEQ R6, R0, done
loop:
	VMOVQ (R5), V0
	VSHUFB V23, V0, V28, V0
	VMUHWU V20, V0, V16
	VSRLW $6, V16, V1
	VMULW V21, V1, V16
	VSUBW V16, V0, V5
	VMUHWU V20, V1, V16
	VSRLW $6, V16, V2
	VMULW V21, V2, V16
	VSUBW V16, V1, V4
	VMUHWU V20, V2, V16
	VSRLW $6, V16, V3
	VMULW V21, V3, V16
	VSUBW V16, V2, V6
	VMUHWU V20, V3, V16
	VSRLW $6, V16, V7
	VMULW V21, V7, V16
	VSUBW V16, V3, V8
	VADDW V22, V7, V7
	VADDW V22, V8, V8
	VADDW V22, V6, V6
	VADDW V22, V4, V4
	VADDW V22, V5, V5
	VSLLW $8, V8, V8
	VSLLW $16, V6, V6
	VSLLW $24, V4, V4
	VORV V8, V7, V7
	VORV V6, V7, V7
	VORV V4, V7, V7
	VSHUFB V24, V7, V28, V9
	VSHUFB V25, V5, V28, V10
	VORV V10, V9, V9
	VSHUFB V26, V7, V28, V11
	VSHUFB V27, V5, V28, V12
	VORV V12, V11, V11
	VMOVQ V9, (R4)
	ADDV $4, R4, R4
	VMOVQ V11, (R4)
	ADDV $16, R4, R4
	ADDV $16, R5, R5
	ADDV $-1, R6, R6
	BNE R6, R0, loop
done:
	RET

DATA a85mrec<>+0(SB)/1, $0xc1
DATA a85mrec<>+1(SB)/1, $0xc0
DATA a85mrec<>+2(SB)/1, $0xc0
DATA a85mrec<>+3(SB)/1, $0xc0
DATA a85mrec<>+4(SB)/1, $0xc1
DATA a85mrec<>+5(SB)/1, $0xc0
DATA a85mrec<>+6(SB)/1, $0xc0
DATA a85mrec<>+7(SB)/1, $0xc0
DATA a85mrec<>+8(SB)/1, $0xc1
DATA a85mrec<>+9(SB)/1, $0xc0
DATA a85mrec<>+10(SB)/1, $0xc0
DATA a85mrec<>+11(SB)/1, $0xc0
DATA a85mrec<>+12(SB)/1, $0xc1
DATA a85mrec<>+13(SB)/1, $0xc0
DATA a85mrec<>+14(SB)/1, $0xc0
DATA a85mrec<>+15(SB)/1, $0xc0
GLOBL a85mrec<>(SB), RODATA|NOPTR, $16

DATA a85c85<>+0(SB)/1, $0x55
DATA a85c85<>+1(SB)/1, $0x00
DATA a85c85<>+2(SB)/1, $0x00
DATA a85c85<>+3(SB)/1, $0x00
DATA a85c85<>+4(SB)/1, $0x55
DATA a85c85<>+5(SB)/1, $0x00
DATA a85c85<>+6(SB)/1, $0x00
DATA a85c85<>+7(SB)/1, $0x00
DATA a85c85<>+8(SB)/1, $0x55
DATA a85c85<>+9(SB)/1, $0x00
DATA a85c85<>+10(SB)/1, $0x00
DATA a85c85<>+11(SB)/1, $0x00
DATA a85c85<>+12(SB)/1, $0x55
DATA a85c85<>+13(SB)/1, $0x00
DATA a85c85<>+14(SB)/1, $0x00
DATA a85c85<>+15(SB)/1, $0x00
GLOBL a85c85<>(SB), RODATA|NOPTR, $16

DATA a85c33<>+0(SB)/1, $0x21
DATA a85c33<>+1(SB)/1, $0x00
DATA a85c33<>+2(SB)/1, $0x00
DATA a85c33<>+3(SB)/1, $0x00
DATA a85c33<>+4(SB)/1, $0x21
DATA a85c33<>+5(SB)/1, $0x00
DATA a85c33<>+6(SB)/1, $0x00
DATA a85c33<>+7(SB)/1, $0x00
DATA a85c33<>+8(SB)/1, $0x21
DATA a85c33<>+9(SB)/1, $0x00
DATA a85c33<>+10(SB)/1, $0x00
DATA a85c33<>+11(SB)/1, $0x00
DATA a85c33<>+12(SB)/1, $0x21
DATA a85c33<>+13(SB)/1, $0x00
DATA a85c33<>+14(SB)/1, $0x00
DATA a85c33<>+15(SB)/1, $0x00
GLOBL a85c33<>(SB), RODATA|NOPTR, $16

DATA a85bswap<>+0(SB)/1, $0x03
DATA a85bswap<>+1(SB)/1, $0x02
DATA a85bswap<>+2(SB)/1, $0x01
DATA a85bswap<>+3(SB)/1, $0x00
DATA a85bswap<>+4(SB)/1, $0x07
DATA a85bswap<>+5(SB)/1, $0x06
DATA a85bswap<>+6(SB)/1, $0x05
DATA a85bswap<>+7(SB)/1, $0x04
DATA a85bswap<>+8(SB)/1, $0x0b
DATA a85bswap<>+9(SB)/1, $0x0a
DATA a85bswap<>+10(SB)/1, $0x09
DATA a85bswap<>+11(SB)/1, $0x08
DATA a85bswap<>+12(SB)/1, $0x0f
DATA a85bswap<>+13(SB)/1, $0x0e
DATA a85bswap<>+14(SB)/1, $0x0d
DATA a85bswap<>+15(SB)/1, $0x0c
GLOBL a85bswap<>(SB), RODATA|NOPTR, $16

DATA a85expA<>+0(SB)/1, $0x00
DATA a85expA<>+1(SB)/1, $0x01
DATA a85expA<>+2(SB)/1, $0x02
DATA a85expA<>+3(SB)/1, $0x03
DATA a85expA<>+4(SB)/1, $0x10
DATA a85expA<>+5(SB)/1, $0x04
DATA a85expA<>+6(SB)/1, $0x05
DATA a85expA<>+7(SB)/1, $0x06
DATA a85expA<>+8(SB)/1, $0x07
DATA a85expA<>+9(SB)/1, $0x10
DATA a85expA<>+10(SB)/1, $0x08
DATA a85expA<>+11(SB)/1, $0x09
DATA a85expA<>+12(SB)/1, $0x0a
DATA a85expA<>+13(SB)/1, $0x0b
DATA a85expA<>+14(SB)/1, $0x10
DATA a85expA<>+15(SB)/1, $0x0c
GLOBL a85expA<>(SB), RODATA|NOPTR, $16

DATA a85d4A<>+0(SB)/1, $0x10
DATA a85d4A<>+1(SB)/1, $0x10
DATA a85d4A<>+2(SB)/1, $0x10
DATA a85d4A<>+3(SB)/1, $0x10
DATA a85d4A<>+4(SB)/1, $0x00
DATA a85d4A<>+5(SB)/1, $0x10
DATA a85d4A<>+6(SB)/1, $0x10
DATA a85d4A<>+7(SB)/1, $0x10
DATA a85d4A<>+8(SB)/1, $0x10
DATA a85d4A<>+9(SB)/1, $0x04
DATA a85d4A<>+10(SB)/1, $0x10
DATA a85d4A<>+11(SB)/1, $0x10
DATA a85d4A<>+12(SB)/1, $0x10
DATA a85d4A<>+13(SB)/1, $0x10
DATA a85d4A<>+14(SB)/1, $0x08
DATA a85d4A<>+15(SB)/1, $0x10
GLOBL a85d4A<>(SB), RODATA|NOPTR, $16

DATA a85expB<>+0(SB)/1, $0x10
DATA a85expB<>+1(SB)/1, $0x04
DATA a85expB<>+2(SB)/1, $0x05
DATA a85expB<>+3(SB)/1, $0x06
DATA a85expB<>+4(SB)/1, $0x07
DATA a85expB<>+5(SB)/1, $0x10
DATA a85expB<>+6(SB)/1, $0x08
DATA a85expB<>+7(SB)/1, $0x09
DATA a85expB<>+8(SB)/1, $0x0a
DATA a85expB<>+9(SB)/1, $0x0b
DATA a85expB<>+10(SB)/1, $0x10
DATA a85expB<>+11(SB)/1, $0x0c
DATA a85expB<>+12(SB)/1, $0x0d
DATA a85expB<>+13(SB)/1, $0x0e
DATA a85expB<>+14(SB)/1, $0x0f
DATA a85expB<>+15(SB)/1, $0x10
GLOBL a85expB<>(SB), RODATA|NOPTR, $16

DATA a85d4B<>+0(SB)/1, $0x00
DATA a85d4B<>+1(SB)/1, $0x10
DATA a85d4B<>+2(SB)/1, $0x10
DATA a85d4B<>+3(SB)/1, $0x10
DATA a85d4B<>+4(SB)/1, $0x10
DATA a85d4B<>+5(SB)/1, $0x04
DATA a85d4B<>+6(SB)/1, $0x10
DATA a85d4B<>+7(SB)/1, $0x10
DATA a85d4B<>+8(SB)/1, $0x10
DATA a85d4B<>+9(SB)/1, $0x10
DATA a85d4B<>+10(SB)/1, $0x08
DATA a85d4B<>+11(SB)/1, $0x10
DATA a85d4B<>+12(SB)/1, $0x10
DATA a85d4B<>+13(SB)/1, $0x10
DATA a85d4B<>+14(SB)/1, $0x10
DATA a85d4B<>+15(SB)/1, $0x0c
GLOBL a85d4B<>(SB), RODATA|NOPTR, $16

