//go:build amd64

package ascii85

import "encoding/ascii85"

// encodeGroups encodes blocks*4 groups of 4 input bytes into 5 base-85 chars
// each (16 input bytes -> 20 chars per block) via SSE. Generated by go-asmgen
// (encode_gen.go), in encode_amd64.s. The caller guarantees none of those groups
// is all-zero, so every group expands to exactly 5 chars.
func encodeGroups(dst, src []byte, blocks int)

// encodeSIMD encodes the leading run of groups (which the caller guarantees
// contains no all-zero group) into 5 chars each, using the SSE kernel for whole
// 4-group blocks and the standard library for the (groups&3) remainder. It
// returns the number of bytes written.
func encodeSIMD(dst, src []byte, groups int) int {
	blocks := groups / 4
	if blocks > 0 {
		encodeGroups(dst, src, blocks)
	}
	done := blocks * 4
	w := done * 5
	if rem := groups - done; rem > 0 {
		w += ascii85.Encode(dst[w:], src[done*4:groups*4])
	}
	return w
}
