//go:build ppc64le

package ascii85

import (
	"encoding/ascii85"

	"golang.org/x/sys/cpu"
)

// encodeGroups encodes blocks*4 groups of 4 input bytes into 5 base-85 chars
// each (16 input bytes -> 20 chars per block) via the VSX/AltiVec vector
// facility. Generated by go-asmgen (encode_ppc64x_gen.go), in encode_ppc64x.s.
// The caller guarantees none of those groups is all-zero. The kernel is built
// entirely from ISA-2.07 (POWER8-baseline) ops — the element-order vector
// load/store is emitted as LXVD2X/STXVD2X + a VPERM byte-reversal instead of the
// ISA-3.0 LXVB16X/STXVB16X — so it runs natively on POWER8 too.
func encodeGroups(dst, src []byte, blocks int)

// hasVSX is the shared dispatch flag for both the encode and decode VSX kernels.
// The kernels are now ISA-2.07 (VSX/AltiVec is the ppc64le baseline, POWER8), so
// they run on every ppc64le host (POWER8 included) — measured on cfarm112
// (POWER8E) to beat the scalar fallback. The previous ISA-3.0 LXVB16X/STXVB16X
// (POWER9-gated) was replaced by LXVD2X/STXVD2X + a VPERM byte-reversal. It is a
// var (not a const) so the dispatch test can also drive the scalar fallback.
var hasVSX = cpu.PPC64.IsPOWER8

// encodeSIMD encodes the leading run of non-zero groups into 5 chars each, using
// the vector kernel for whole 4-group blocks and the standard library for the
// (groups&3) remainder. On POWER8 (no LXVB16X/STXVB16X) it encodes every group
// with a tight scalar loop. It returns the number of bytes written.
func encodeSIMD(dst, src []byte, groups int) int {
	if !hasVSX {
		return encodeScalar(dst, src, groups)
	}
	blocks := groups / 4
	if blocks > 0 {
		encodeGroups(dst, src, blocks)
	}
	done := blocks * 4
	w := done * 5
	if rem := groups - done; rem > 0 {
		w += ascii85.Encode(dst[w:], src[done*4:groups*4])
	}
	return w
}

// encodeScalar encodes the leading run of non-zero groups with a tight scalar
// loop (the POWER8 fallback). The caller guarantees src[:groups*4] contains no
// all-zero group, so each group always expands to exactly 5 chars and is
// byte-identical to encoding/ascii85's output for those groups.
func encodeScalar(dst, src []byte, groups int) int {
	di := 0
	for g := 0; g < groups; g++ {
		s := src[g*4:]
		v := uint32(s[0])<<24 | uint32(s[1])<<16 | uint32(s[2])<<8 | uint32(s[3])
		d := dst[di : di+5 : di+5]
		d[4] = '!' + byte(v%85)
		v /= 85
		d[3] = '!' + byte(v%85)
		v /= 85
		d[2] = '!' + byte(v%85)
		v /= 85
		d[1] = '!' + byte(v%85)
		v /= 85
		d[0] = '!' + byte(v)
		di += 5
	}
	return di
}
