//go:build riscv64

package ascii85

import "encoding/ascii85"

// encodeGroups encodes blocks*4 groups of 4 input bytes into 5 base-85 chars
// each (16 input bytes -> 20 chars per block) via the RVV vector extension.
// Generated by go-asmgen (encode_riscv64_gen.go), in encode_riscv64.s. It pins
// vl=4/16 with VSETIVLI and so requires the V extension with VLEN>=128 (the GORISCV64=rva23u64
// baseline and every V-capable core); the caller guarantees none of those groups
// is all-zero.
func encodeGroups(dst, src []byte, blocks int)

// encodeSIMD encodes the leading run of non-zero groups into 5 chars each, using
// the RVV kernel for whole 4-group blocks and the standard library for the
// (groups&3) remainder. It returns the number of bytes written.
func encodeSIMD(dst, src []byte, groups int) int {
	blocks := groups / 4
	if blocks > 0 {
		encodeGroups(dst, src, blocks)
	}
	done := blocks * 4
	w := done * 5
	if rem := groups - done; rem > 0 {
		w += ascii85.Encode(dst[w:], src[done*4:groups*4])
	}
	return w
}
