// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·encodeGroups(SB), NOSPLIT, $0-56
	MOV dst_base+0(FP), X5
	MOV src_base+24(FP), X6
	MOV blocks+48(FP), X7
	VSETIVLI $16, E8, M1, TA, MA, X28
	MOV $a85bswap<>(SB), X29
	VLE8V (X29), V20
	MOV $a85expA<>(SB), X29
	VLE8V (X29), V21
	MOV $a85d4A<>(SB), X29
	VLE8V (X29), V22
	MOV $a85expB<>(SB), X29
	VLE8V (X29), V23
	MOV $a85d4B<>(SB), X29
	VLE8V (X29), V24
	VSETIVLI $4, E32, M1, TA, MA, X28
	MOV $a85mrec<>(SB), X29
	VLE32V (X29), V25
	MOV $85, X30
	VMVVX X30, V26
	MOV $33, X31
	BEQ X7, X0, done
loop:
	VSETIVLI $16, E8, M1, TA, MA, X28
	VLE8V (X6), V0
	VRGATHERVV V20, V0, V1
	VSETIVLI $4, E32, M1, TA, MA, X28
	VMULHUVV V25, V1, V16
	VSRLVI $6, V16, V2
	VMULVV V26, V2, V16
	VSUBVV V16, V1, V6
	VMULHUVV V25, V2, V16
	VSRLVI $6, V16, V3
	VMULVV V26, V3, V16
	VSUBVV V16, V2, V5
	VMULHUVV V25, V3, V16
	VSRLVI $6, V16, V4
	VMULVV V26, V4, V16
	VSUBVV V16, V3, V7
	VMULHUVV V25, V4, V16
	VSRLVI $6, V16, V8
	VMULVV V26, V8, V16
	VSUBVV V16, V4, V9
	VADDVX X31, V8, V8
	VADDVX X31, V9, V9
	VADDVX X31, V7, V7
	VADDVX X31, V5, V5
	VADDVX X31, V6, V6
	VSLLVI $8, V9, V9
	VSLLVI $16, V7, V7
	VSLLVI $24, V5, V5
	VORVV V9, V8, V8
	VORVV V7, V8, V8
	VORVV V5, V8, V8
	VSETIVLI $16, E8, M1, TA, MA, X28
	VRGATHERVV V21, V8, V10
	VRGATHERVV V22, V6, V11
	VORVV V11, V10, V10
	VRGATHERVV V23, V8, V12
	VRGATHERVV V24, V6, V13
	VORVV V13, V12, V12
	VSE8V V10, (X5)
	ADD $4, X5
	VSE8V V12, (X5)
	ADD $16, X5
	ADD $16, X6
	ADD $-1, X7
	BNE X7, X0, loop
done:
	RET

DATA a85mrec<>+0(SB)/1, $0xc1
DATA a85mrec<>+1(SB)/1, $0xc0
DATA a85mrec<>+2(SB)/1, $0xc0
DATA a85mrec<>+3(SB)/1, $0xc0
DATA a85mrec<>+4(SB)/1, $0xc1
DATA a85mrec<>+5(SB)/1, $0xc0
DATA a85mrec<>+6(SB)/1, $0xc0
DATA a85mrec<>+7(SB)/1, $0xc0
DATA a85mrec<>+8(SB)/1, $0xc1
DATA a85mrec<>+9(SB)/1, $0xc0
DATA a85mrec<>+10(SB)/1, $0xc0
DATA a85mrec<>+11(SB)/1, $0xc0
DATA a85mrec<>+12(SB)/1, $0xc1
DATA a85mrec<>+13(SB)/1, $0xc0
DATA a85mrec<>+14(SB)/1, $0xc0
DATA a85mrec<>+15(SB)/1, $0xc0
GLOBL a85mrec<>(SB), RODATA|NOPTR, $16

DATA a85bswap<>+0(SB)/1, $0x03
DATA a85bswap<>+1(SB)/1, $0x02
DATA a85bswap<>+2(SB)/1, $0x01
DATA a85bswap<>+3(SB)/1, $0x00
DATA a85bswap<>+4(SB)/1, $0x07
DATA a85bswap<>+5(SB)/1, $0x06
DATA a85bswap<>+6(SB)/1, $0x05
DATA a85bswap<>+7(SB)/1, $0x04
DATA a85bswap<>+8(SB)/1, $0x0b
DATA a85bswap<>+9(SB)/1, $0x0a
DATA a85bswap<>+10(SB)/1, $0x09
DATA a85bswap<>+11(SB)/1, $0x08
DATA a85bswap<>+12(SB)/1, $0x0f
DATA a85bswap<>+13(SB)/1, $0x0e
DATA a85bswap<>+14(SB)/1, $0x0d
DATA a85bswap<>+15(SB)/1, $0x0c
GLOBL a85bswap<>(SB), RODATA|NOPTR, $16

DATA a85expA<>+0(SB)/1, $0x00
DATA a85expA<>+1(SB)/1, $0x01
DATA a85expA<>+2(SB)/1, $0x02
DATA a85expA<>+3(SB)/1, $0x03
DATA a85expA<>+4(SB)/1, $0xff
DATA a85expA<>+5(SB)/1, $0x04
DATA a85expA<>+6(SB)/1, $0x05
DATA a85expA<>+7(SB)/1, $0x06
DATA a85expA<>+8(SB)/1, $0x07
DATA a85expA<>+9(SB)/1, $0xff
DATA a85expA<>+10(SB)/1, $0x08
DATA a85expA<>+11(SB)/1, $0x09
DATA a85expA<>+12(SB)/1, $0x0a
DATA a85expA<>+13(SB)/1, $0x0b
DATA a85expA<>+14(SB)/1, $0xff
DATA a85expA<>+15(SB)/1, $0x0c
GLOBL a85expA<>(SB), RODATA|NOPTR, $16

DATA a85d4A<>+0(SB)/1, $0xff
DATA a85d4A<>+1(SB)/1, $0xff
DATA a85d4A<>+2(SB)/1, $0xff
DATA a85d4A<>+3(SB)/1, $0xff
DATA a85d4A<>+4(SB)/1, $0x00
DATA a85d4A<>+5(SB)/1, $0xff
DATA a85d4A<>+6(SB)/1, $0xff
DATA a85d4A<>+7(SB)/1, $0xff
DATA a85d4A<>+8(SB)/1, $0xff
DATA a85d4A<>+9(SB)/1, $0x04
DATA a85d4A<>+10(SB)/1, $0xff
DATA a85d4A<>+11(SB)/1, $0xff
DATA a85d4A<>+12(SB)/1, $0xff
DATA a85d4A<>+13(SB)/1, $0xff
DATA a85d4A<>+14(SB)/1, $0x08
DATA a85d4A<>+15(SB)/1, $0xff
GLOBL a85d4A<>(SB), RODATA|NOPTR, $16

DATA a85expB<>+0(SB)/1, $0xff
DATA a85expB<>+1(SB)/1, $0x04
DATA a85expB<>+2(SB)/1, $0x05
DATA a85expB<>+3(SB)/1, $0x06
DATA a85expB<>+4(SB)/1, $0x07
DATA a85expB<>+5(SB)/1, $0xff
DATA a85expB<>+6(SB)/1, $0x08
DATA a85expB<>+7(SB)/1, $0x09
DATA a85expB<>+8(SB)/1, $0x0a
DATA a85expB<>+9(SB)/1, $0x0b
DATA a85expB<>+10(SB)/1, $0xff
DATA a85expB<>+11(SB)/1, $0x0c
DATA a85expB<>+12(SB)/1, $0x0d
DATA a85expB<>+13(SB)/1, $0x0e
DATA a85expB<>+14(SB)/1, $0x0f
DATA a85expB<>+15(SB)/1, $0xff
GLOBL a85expB<>(SB), RODATA|NOPTR, $16

DATA a85d4B<>+0(SB)/1, $0x00
DATA a85d4B<>+1(SB)/1, $0xff
DATA a85d4B<>+2(SB)/1, $0xff
DATA a85d4B<>+3(SB)/1, $0xff
DATA a85d4B<>+4(SB)/1, $0xff
DATA a85d4B<>+5(SB)/1, $0x04
DATA a85d4B<>+6(SB)/1, $0xff
DATA a85d4B<>+7(SB)/1, $0xff
DATA a85d4B<>+8(SB)/1, $0xff
DATA a85d4B<>+9(SB)/1, $0xff
DATA a85d4B<>+10(SB)/1, $0x08
DATA a85d4B<>+11(SB)/1, $0xff
DATA a85d4B<>+12(SB)/1, $0xff
DATA a85d4B<>+13(SB)/1, $0xff
DATA a85d4B<>+14(SB)/1, $0xff
DATA a85d4B<>+15(SB)/1, $0x0c
GLOBL a85d4B<>(SB), RODATA|NOPTR, $16

