// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·encodeGroups(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD blocks+48(FP), R3
	MOVD $a85mrec<>(SB), R4
	VL (R4), V20
	MOVD $a85c85<>(SB), R4
	VL (R4), V21
	MOVD $a85c33<>(SB), R4
	VL (R4), V22
	MOVD $a85expLo<>(SB), R4
	VL (R4), V23
	MOVD $a85expHi<>(SB), R4
	VL (R4), V24
	MOVD $a85d4Lo<>(SB), R4
	VL (R4), V25
	MOVD $a85d4Hi<>(SB), R4
	VL (R4), V26
	CMPBEQ R3, $0, done
loop:
	VL (R2), V0
	VMLHF V0, V20, V16
	VESRLF $6, V16, V1
	VMLF V1, V21, V17
	VSF V17, V0, V5
	VMLHF V1, V20, V16
	VESRLF $6, V16, V2
	VMLF V2, V21, V17
	VSF V17, V1, V4
	VMLHF V2, V20, V16
	VESRLF $6, V16, V3
	VMLF V3, V21, V17
	VSF V17, V2, V6
	VMLHF V3, V20, V16
	VESRLF $6, V16, V7
	VMLF V7, V21, V17
	VSF V17, V3, V8
	VAF V22, V7, V7
	VAF V22, V8, V8
	VAF V22, V6, V6
	VAF V22, V4, V4
	VAF V22, V5, V5
	VESLF $24, V7, V7
	VESLF $24, V8, V8
	VESLF $24, V6, V6
	VESLF $24, V4, V4
	VESLF $24, V5, V5
	VZERO V19
	VSLDB $15, V19, V8, V9
	VSLDB $14, V19, V6, V10
	VSLDB $13, V19, V4, V11
	VO V9, V7, V7
	VO V10, V7, V7
	VO V11, V7, V7
	VPERM V7, V19, V23, V12
	VPERM V5, V19, V25, V13
	VO V13, V12, V12
	VPERM V7, V19, V24, V14
	VPERM V5, V19, V26, V15
	VO V15, V14, V14
	VST V12, (R1)
	VSTEF $0, V14, 16(R1)
	ADD $16, R2
	ADD $20, R1
	ADD $-1, R3
	CMPBNE R3, $0, loop
done:
	RET

DATA a85mrec<>+0(SB)/1, $0xc0
DATA a85mrec<>+1(SB)/1, $0xc0
DATA a85mrec<>+2(SB)/1, $0xc0
DATA a85mrec<>+3(SB)/1, $0xc1
DATA a85mrec<>+4(SB)/1, $0xc0
DATA a85mrec<>+5(SB)/1, $0xc0
DATA a85mrec<>+6(SB)/1, $0xc0
DATA a85mrec<>+7(SB)/1, $0xc1
DATA a85mrec<>+8(SB)/1, $0xc0
DATA a85mrec<>+9(SB)/1, $0xc0
DATA a85mrec<>+10(SB)/1, $0xc0
DATA a85mrec<>+11(SB)/1, $0xc1
DATA a85mrec<>+12(SB)/1, $0xc0
DATA a85mrec<>+13(SB)/1, $0xc0
DATA a85mrec<>+14(SB)/1, $0xc0
DATA a85mrec<>+15(SB)/1, $0xc1
GLOBL a85mrec<>(SB), RODATA|NOPTR, $16

DATA a85c85<>+0(SB)/1, $0x00
DATA a85c85<>+1(SB)/1, $0x00
DATA a85c85<>+2(SB)/1, $0x00
DATA a85c85<>+3(SB)/1, $0x55
DATA a85c85<>+4(SB)/1, $0x00
DATA a85c85<>+5(SB)/1, $0x00
DATA a85c85<>+6(SB)/1, $0x00
DATA a85c85<>+7(SB)/1, $0x55
DATA a85c85<>+8(SB)/1, $0x00
DATA a85c85<>+9(SB)/1, $0x00
DATA a85c85<>+10(SB)/1, $0x00
DATA a85c85<>+11(SB)/1, $0x55
DATA a85c85<>+12(SB)/1, $0x00
DATA a85c85<>+13(SB)/1, $0x00
DATA a85c85<>+14(SB)/1, $0x00
DATA a85c85<>+15(SB)/1, $0x55
GLOBL a85c85<>(SB), RODATA|NOPTR, $16

DATA a85c33<>+0(SB)/1, $0x00
DATA a85c33<>+1(SB)/1, $0x00
DATA a85c33<>+2(SB)/1, $0x00
DATA a85c33<>+3(SB)/1, $0x21
DATA a85c33<>+4(SB)/1, $0x00
DATA a85c33<>+5(SB)/1, $0x00
DATA a85c33<>+6(SB)/1, $0x00
DATA a85c33<>+7(SB)/1, $0x21
DATA a85c33<>+8(SB)/1, $0x00
DATA a85c33<>+9(SB)/1, $0x00
DATA a85c33<>+10(SB)/1, $0x00
DATA a85c33<>+11(SB)/1, $0x21
DATA a85c33<>+12(SB)/1, $0x00
DATA a85c33<>+13(SB)/1, $0x00
DATA a85c33<>+14(SB)/1, $0x00
DATA a85c33<>+15(SB)/1, $0x21
GLOBL a85c33<>(SB), RODATA|NOPTR, $16

DATA a85expLo<>+0(SB)/1, $0x00
DATA a85expLo<>+1(SB)/1, $0x01
DATA a85expLo<>+2(SB)/1, $0x02
DATA a85expLo<>+3(SB)/1, $0x03
DATA a85expLo<>+4(SB)/1, $0x10
DATA a85expLo<>+5(SB)/1, $0x04
DATA a85expLo<>+6(SB)/1, $0x05
DATA a85expLo<>+7(SB)/1, $0x06
DATA a85expLo<>+8(SB)/1, $0x07
DATA a85expLo<>+9(SB)/1, $0x10
DATA a85expLo<>+10(SB)/1, $0x08
DATA a85expLo<>+11(SB)/1, $0x09
DATA a85expLo<>+12(SB)/1, $0x0a
DATA a85expLo<>+13(SB)/1, $0x0b
DATA a85expLo<>+14(SB)/1, $0x10
DATA a85expLo<>+15(SB)/1, $0x0c
GLOBL a85expLo<>(SB), RODATA|NOPTR, $16

DATA a85expHi<>+0(SB)/1, $0x0d
DATA a85expHi<>+1(SB)/1, $0x0e
DATA a85expHi<>+2(SB)/1, $0x0f
DATA a85expHi<>+3(SB)/1, $0x10
DATA a85expHi<>+4(SB)/1, $0x10
DATA a85expHi<>+5(SB)/1, $0x10
DATA a85expHi<>+6(SB)/1, $0x10
DATA a85expHi<>+7(SB)/1, $0x10
DATA a85expHi<>+8(SB)/1, $0x10
DATA a85expHi<>+9(SB)/1, $0x10
DATA a85expHi<>+10(SB)/1, $0x10
DATA a85expHi<>+11(SB)/1, $0x10
DATA a85expHi<>+12(SB)/1, $0x10
DATA a85expHi<>+13(SB)/1, $0x10
DATA a85expHi<>+14(SB)/1, $0x10
DATA a85expHi<>+15(SB)/1, $0x10
GLOBL a85expHi<>(SB), RODATA|NOPTR, $16

DATA a85d4Lo<>+0(SB)/1, $0x10
DATA a85d4Lo<>+1(SB)/1, $0x10
DATA a85d4Lo<>+2(SB)/1, $0x10
DATA a85d4Lo<>+3(SB)/1, $0x10
DATA a85d4Lo<>+4(SB)/1, $0x00
DATA a85d4Lo<>+5(SB)/1, $0x10
DATA a85d4Lo<>+6(SB)/1, $0x10
DATA a85d4Lo<>+7(SB)/1, $0x10
DATA a85d4Lo<>+8(SB)/1, $0x10
DATA a85d4Lo<>+9(SB)/1, $0x04
DATA a85d4Lo<>+10(SB)/1, $0x10
DATA a85d4Lo<>+11(SB)/1, $0x10
DATA a85d4Lo<>+12(SB)/1, $0x10
DATA a85d4Lo<>+13(SB)/1, $0x10
DATA a85d4Lo<>+14(SB)/1, $0x08
DATA a85d4Lo<>+15(SB)/1, $0x10
GLOBL a85d4Lo<>(SB), RODATA|NOPTR, $16

DATA a85d4Hi<>+0(SB)/1, $0x10
DATA a85d4Hi<>+1(SB)/1, $0x10
DATA a85d4Hi<>+2(SB)/1, $0x10
DATA a85d4Hi<>+3(SB)/1, $0x0c
DATA a85d4Hi<>+4(SB)/1, $0x10
DATA a85d4Hi<>+5(SB)/1, $0x10
DATA a85d4Hi<>+6(SB)/1, $0x10
DATA a85d4Hi<>+7(SB)/1, $0x10
DATA a85d4Hi<>+8(SB)/1, $0x10
DATA a85d4Hi<>+9(SB)/1, $0x10
DATA a85d4Hi<>+10(SB)/1, $0x10
DATA a85d4Hi<>+11(SB)/1, $0x10
DATA a85d4Hi<>+12(SB)/1, $0x10
DATA a85d4Hi<>+13(SB)/1, $0x10
DATA a85d4Hi<>+14(SB)/1, $0x10
DATA a85d4Hi<>+15(SB)/1, $0x10
GLOBL a85d4Hi<>(SB), RODATA|NOPTR, $16

