// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·encodeGroups(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ blocks+48(FP), CX
	MOVOU a85bswap<>+0(SB), X8
	MOVOU a85mrec<>+0(SB), X9
	MOVOU a85c85<>+0(SB), X10
	MOVOU a85c33<>+0(SB), X11
	MOVOU a85oddmask<>+0(SB), X12
	TESTQ CX, CX
	JZ done
blkloop:
	MOVOU (SI), X0
	PSHUFB X8, X0
	MOVO X0, X6
	PMULULQ X9, X6
	PSRLQ $32, X6
	MOVO X0, X7
	PSRLO $4, X7
	PMULULQ X9, X7
	PSRLQ $32, X7
	PSLLO $4, X7
	PAND X12, X7
	MOVO X12, X5
	PANDN X6, X5
	POR X7, X5
	PSRLL $6, X5
	MOVO X5, X1
	MOVO X1, X13
	PMULLD X10, X13
	MOVO X0, X4
	PSUBL X13, X4
	MOVO X1, X6
	PMULULQ X9, X6
	PSRLQ $32, X6
	MOVO X1, X7
	PSRLO $4, X7
	PMULULQ X9, X7
	PSRLQ $32, X7
	PSLLO $4, X7
	PAND X12, X7
	MOVO X12, X5
	PANDN X6, X5
	POR X7, X5
	PSRLL $6, X5
	MOVO X5, X2
	MOVO X2, X13
	PMULLD X10, X13
	MOVO X1, X3
	PSUBL X13, X3
	MOVO X2, X6
	PMULULQ X9, X6
	PSRLQ $32, X6
	MOVO X2, X7
	PSRLO $4, X7
	PMULULQ X9, X7
	PSRLQ $32, X7
	PSLLO $4, X7
	PAND X12, X7
	MOVO X12, X5
	PANDN X6, X5
	POR X7, X5
	PSRLL $6, X5
	MOVO X5, X1
	MOVO X1, X13
	PMULLD X10, X13
	PSUBL X13, X2
	MOVO X1, X6
	PMULULQ X9, X6
	PSRLQ $32, X6
	MOVO X1, X7
	PSRLO $4, X7
	PMULULQ X9, X7
	PSRLQ $32, X7
	PSLLO $4, X7
	PAND X12, X7
	MOVO X12, X5
	PANDN X6, X5
	POR X7, X5
	PSRLL $6, X5
	MOVO X5, X13
	PMULLD X10, X13
	PSUBL X13, X1
	PADDL X11, X5
	PADDL X11, X1
	PADDL X11, X2
	PADDL X11, X3
	PADDL X11, X4
	MOVO X1, X6
	PSLLO $1, X6
	MOVO X2, X7
	PSLLO $2, X7
	MOVO X3, X13
	PSLLO $3, X13
	POR X6, X5
	POR X7, X5
	POR X13, X5
	MOVOU a85expLo<>+0(SB), X6
	MOVO X5, X7
	PSHUFB X6, X7
	MOVOU a85d4Lo<>+0(SB), X6
	MOVO X4, X13
	PSHUFB X6, X13
	POR X13, X7
	MOVOU a85expHi<>+0(SB), X6
	MOVO X5, X0
	PSHUFB X6, X0
	MOVOU a85d4Hi<>+0(SB), X6
	PSHUFB X6, X4
	POR X4, X0
	MOVOU X7, (DI)
	MOVL X0, 16(DI)
	ADDQ $16, SI
	ADDQ $20, DI
	DECQ CX
	JNZ blkloop
done:
	RET

DATA a85bswap<>+0(SB)/1, $0x03
DATA a85bswap<>+1(SB)/1, $0x02
DATA a85bswap<>+2(SB)/1, $0x01
DATA a85bswap<>+3(SB)/1, $0x00
DATA a85bswap<>+4(SB)/1, $0x07
DATA a85bswap<>+5(SB)/1, $0x06
DATA a85bswap<>+6(SB)/1, $0x05
DATA a85bswap<>+7(SB)/1, $0x04
DATA a85bswap<>+8(SB)/1, $0x0b
DATA a85bswap<>+9(SB)/1, $0x0a
DATA a85bswap<>+10(SB)/1, $0x09
DATA a85bswap<>+11(SB)/1, $0x08
DATA a85bswap<>+12(SB)/1, $0x0f
DATA a85bswap<>+13(SB)/1, $0x0e
DATA a85bswap<>+14(SB)/1, $0x0d
DATA a85bswap<>+15(SB)/1, $0x0c
GLOBL a85bswap<>(SB), RODATA|NOPTR, $16

DATA a85mrec<>+0(SB)/1, $0xc1
DATA a85mrec<>+1(SB)/1, $0xc0
DATA a85mrec<>+2(SB)/1, $0xc0
DATA a85mrec<>+3(SB)/1, $0xc0
DATA a85mrec<>+4(SB)/1, $0xc1
DATA a85mrec<>+5(SB)/1, $0xc0
DATA a85mrec<>+6(SB)/1, $0xc0
DATA a85mrec<>+7(SB)/1, $0xc0
DATA a85mrec<>+8(SB)/1, $0xc1
DATA a85mrec<>+9(SB)/1, $0xc0
DATA a85mrec<>+10(SB)/1, $0xc0
DATA a85mrec<>+11(SB)/1, $0xc0
DATA a85mrec<>+12(SB)/1, $0xc1
DATA a85mrec<>+13(SB)/1, $0xc0
DATA a85mrec<>+14(SB)/1, $0xc0
DATA a85mrec<>+15(SB)/1, $0xc0
GLOBL a85mrec<>(SB), RODATA|NOPTR, $16

DATA a85c85<>+0(SB)/1, $0x55
DATA a85c85<>+1(SB)/1, $0x00
DATA a85c85<>+2(SB)/1, $0x00
DATA a85c85<>+3(SB)/1, $0x00
DATA a85c85<>+4(SB)/1, $0x55
DATA a85c85<>+5(SB)/1, $0x00
DATA a85c85<>+6(SB)/1, $0x00
DATA a85c85<>+7(SB)/1, $0x00
DATA a85c85<>+8(SB)/1, $0x55
DATA a85c85<>+9(SB)/1, $0x00
DATA a85c85<>+10(SB)/1, $0x00
DATA a85c85<>+11(SB)/1, $0x00
DATA a85c85<>+12(SB)/1, $0x55
DATA a85c85<>+13(SB)/1, $0x00
DATA a85c85<>+14(SB)/1, $0x00
DATA a85c85<>+15(SB)/1, $0x00
GLOBL a85c85<>(SB), RODATA|NOPTR, $16

DATA a85c33<>+0(SB)/1, $0x21
DATA a85c33<>+1(SB)/1, $0x00
DATA a85c33<>+2(SB)/1, $0x00
DATA a85c33<>+3(SB)/1, $0x00
DATA a85c33<>+4(SB)/1, $0x21
DATA a85c33<>+5(SB)/1, $0x00
DATA a85c33<>+6(SB)/1, $0x00
DATA a85c33<>+7(SB)/1, $0x00
DATA a85c33<>+8(SB)/1, $0x21
DATA a85c33<>+9(SB)/1, $0x00
DATA a85c33<>+10(SB)/1, $0x00
DATA a85c33<>+11(SB)/1, $0x00
DATA a85c33<>+12(SB)/1, $0x21
DATA a85c33<>+13(SB)/1, $0x00
DATA a85c33<>+14(SB)/1, $0x00
DATA a85c33<>+15(SB)/1, $0x00
GLOBL a85c33<>(SB), RODATA|NOPTR, $16

DATA a85oddmask<>+0(SB)/1, $0x00
DATA a85oddmask<>+1(SB)/1, $0x00
DATA a85oddmask<>+2(SB)/1, $0x00
DATA a85oddmask<>+3(SB)/1, $0x00
DATA a85oddmask<>+4(SB)/1, $0xff
DATA a85oddmask<>+5(SB)/1, $0xff
DATA a85oddmask<>+6(SB)/1, $0xff
DATA a85oddmask<>+7(SB)/1, $0xff
DATA a85oddmask<>+8(SB)/1, $0x00
DATA a85oddmask<>+9(SB)/1, $0x00
DATA a85oddmask<>+10(SB)/1, $0x00
DATA a85oddmask<>+11(SB)/1, $0x00
DATA a85oddmask<>+12(SB)/1, $0xff
DATA a85oddmask<>+13(SB)/1, $0xff
DATA a85oddmask<>+14(SB)/1, $0xff
DATA a85oddmask<>+15(SB)/1, $0xff
GLOBL a85oddmask<>(SB), RODATA|NOPTR, $16

DATA a85expLo<>+0(SB)/1, $0x00
DATA a85expLo<>+1(SB)/1, $0x01
DATA a85expLo<>+2(SB)/1, $0x02
DATA a85expLo<>+3(SB)/1, $0x03
DATA a85expLo<>+4(SB)/1, $0x80
DATA a85expLo<>+5(SB)/1, $0x04
DATA a85expLo<>+6(SB)/1, $0x05
DATA a85expLo<>+7(SB)/1, $0x06
DATA a85expLo<>+8(SB)/1, $0x07
DATA a85expLo<>+9(SB)/1, $0x80
DATA a85expLo<>+10(SB)/1, $0x08
DATA a85expLo<>+11(SB)/1, $0x09
DATA a85expLo<>+12(SB)/1, $0x0a
DATA a85expLo<>+13(SB)/1, $0x0b
DATA a85expLo<>+14(SB)/1, $0x80
DATA a85expLo<>+15(SB)/1, $0x0c
GLOBL a85expLo<>(SB), RODATA|NOPTR, $16

DATA a85expHi<>+0(SB)/1, $0x0d
DATA a85expHi<>+1(SB)/1, $0x0e
DATA a85expHi<>+2(SB)/1, $0x0f
DATA a85expHi<>+3(SB)/1, $0x80
DATA a85expHi<>+4(SB)/1, $0x80
DATA a85expHi<>+5(SB)/1, $0x80
DATA a85expHi<>+6(SB)/1, $0x80
DATA a85expHi<>+7(SB)/1, $0x80
DATA a85expHi<>+8(SB)/1, $0x80
DATA a85expHi<>+9(SB)/1, $0x80
DATA a85expHi<>+10(SB)/1, $0x80
DATA a85expHi<>+11(SB)/1, $0x80
DATA a85expHi<>+12(SB)/1, $0x80
DATA a85expHi<>+13(SB)/1, $0x80
DATA a85expHi<>+14(SB)/1, $0x80
DATA a85expHi<>+15(SB)/1, $0x80
GLOBL a85expHi<>(SB), RODATA|NOPTR, $16

DATA a85d4Lo<>+0(SB)/1, $0x80
DATA a85d4Lo<>+1(SB)/1, $0x80
DATA a85d4Lo<>+2(SB)/1, $0x80
DATA a85d4Lo<>+3(SB)/1, $0x80
DATA a85d4Lo<>+4(SB)/1, $0x00
DATA a85d4Lo<>+5(SB)/1, $0x80
DATA a85d4Lo<>+6(SB)/1, $0x80
DATA a85d4Lo<>+7(SB)/1, $0x80
DATA a85d4Lo<>+8(SB)/1, $0x80
DATA a85d4Lo<>+9(SB)/1, $0x04
DATA a85d4Lo<>+10(SB)/1, $0x80
DATA a85d4Lo<>+11(SB)/1, $0x80
DATA a85d4Lo<>+12(SB)/1, $0x80
DATA a85d4Lo<>+13(SB)/1, $0x80
DATA a85d4Lo<>+14(SB)/1, $0x08
DATA a85d4Lo<>+15(SB)/1, $0x80
GLOBL a85d4Lo<>(SB), RODATA|NOPTR, $16

DATA a85d4Hi<>+0(SB)/1, $0x80
DATA a85d4Hi<>+1(SB)/1, $0x80
DATA a85d4Hi<>+2(SB)/1, $0x80
DATA a85d4Hi<>+3(SB)/1, $0x0c
DATA a85d4Hi<>+4(SB)/1, $0x80
DATA a85d4Hi<>+5(SB)/1, $0x80
DATA a85d4Hi<>+6(SB)/1, $0x80
DATA a85d4Hi<>+7(SB)/1, $0x80
DATA a85d4Hi<>+8(SB)/1, $0x80
DATA a85d4Hi<>+9(SB)/1, $0x80
DATA a85d4Hi<>+10(SB)/1, $0x80
DATA a85d4Hi<>+11(SB)/1, $0x80
DATA a85d4Hi<>+12(SB)/1, $0x80
DATA a85d4Hi<>+13(SB)/1, $0x80
DATA a85d4Hi<>+14(SB)/1, $0x80
DATA a85d4Hi<>+15(SB)/1, $0x80
GLOBL a85d4Hi<>(SB), RODATA|NOPTR, $16

