//go:build ppc64le

package ascii85

import (
	"encoding/ascii85"

	"golang.org/x/sys/cpu"
)

// encodeGroups encodes blocks*4 groups of 4 input bytes into 5 base-85 chars
// each (16 input bytes -> 20 chars per block) via the VSX/AltiVec vector
// facility. Generated by go-asmgen (encode_ppc64x_gen.go), in encode_ppc64x.s.
// The caller guarantees none of those groups is all-zero. The kernel uses
// ISA-3.0 (POWER9) instructions (LXVB16X/STXVB16X), which raise SIGILL on
// POWER8, so it runs only when hasVSX reports POWER9+.
func encodeGroups(dst, src []byte, blocks int)

// hasVSX is the shared dispatch flag for both the encode and decode VSX kernels.
// They emit ISA-3.0 (POWER9) instructions (LXVB16X/STXVB16X) that are illegal on
// POWER8, so they are gated on POWER9 detection; on POWER8 the kernels are never
// called and a tight scalar loop (identical to the portable generic build) does
// all the work. It is a var (not a const) so the dispatch test can also drive the
// no-SIMD fallback on a POWER9+ host.
var hasVSX = cpu.PPC64.IsPOWER9

// encodeSIMD encodes the leading run of non-zero groups into 5 chars each, using
// the vector kernel for whole 4-group blocks and the standard library for the
// (groups&3) remainder. On POWER8 (no LXVB16X/STXVB16X) it encodes every group
// with a tight scalar loop. It returns the number of bytes written.
func encodeSIMD(dst, src []byte, groups int) int {
	if !hasVSX {
		return encodeScalar(dst, src, groups)
	}
	blocks := groups / 4
	if blocks > 0 {
		encodeGroups(dst, src, blocks)
	}
	done := blocks * 4
	w := done * 5
	if rem := groups - done; rem > 0 {
		w += ascii85.Encode(dst[w:], src[done*4:groups*4])
	}
	return w
}

// encodeScalar encodes the leading run of non-zero groups with a tight scalar
// loop (the POWER8 fallback). The caller guarantees src[:groups*4] contains no
// all-zero group, so each group always expands to exactly 5 chars and is
// byte-identical to encoding/ascii85's output for those groups.
func encodeScalar(dst, src []byte, groups int) int {
	di := 0
	for g := 0; g < groups; g++ {
		s := src[g*4:]
		v := uint32(s[0])<<24 | uint32(s[1])<<16 | uint32(s[2])<<8 | uint32(s[3])
		d := dst[di : di+5 : di+5]
		d[4] = '!' + byte(v%85)
		v /= 85
		d[3] = '!' + byte(v%85)
		v /= 85
		d[2] = '!' + byte(v%85)
		v /= 85
		d[1] = '!' + byte(v%85)
		v /= 85
		d[0] = '!' + byte(v)
		di += 5
	}
	return di
}
